title: My Awesome Site
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my awesome site. This is the place where I share my projects and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
theme: minima

# Build settings
markdown: kramdown